version: '3'
services:
  case-server:
    image: case-server:v1.0.6
    container_name: agileTC-caseserver
    env_file:
      - ./agile.env
    command: sh -c "cd /workspace/app/ && java -jar case-server-1.0-SNAPSHOT.jar"
    # docker 端口映射,如果宿主机 8082 端口被占用需要更改
    ports:
      - "8084:8094"
    depends_on:
      - mysql
    restart: always
    networks:
      - agile-net
  mysql:
    image: mysql:5.7.33
    container_name: agileTC-mysql
    env_file:
      - ./agile.env
    # 挂载到宿主机目录 /data/mysql/TCdata
    volumes:
      - /data/mysql/TCdata:/var/lib/mysql
      - ./case-server/sql/case-server.sql:/docker-entrypoint-initdb.d/case-server.sql
    # docker 端口映射,如果宿主机 6666 端口被占用需要更改
    ports:
      - "6666:3306"
    restart: always
    networks:
      - agile-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: --init-file /docker-entrypoint-initdb.d/case-server.sql
networks:
  agile-net:
    driver: bridge
